# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:05:47+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class AcknowledgeFlowEnabled(RootModel[bool]):
    root: bool


class AlarmModelArn(RootModel[str]):
    root: str


class AlarmModelDescription(RootModel[constr(max_length=128)]):
    root: constr(max_length=128)


class AlarmModelName(
    RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=128)]
):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=128)


class AlarmModelVersion(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class AlarmModelVersionStatus(Enum):
    ACTIVE = 'ACTIVE'
    ACTIVATING = 'ACTIVATING'
    INACTIVE = 'INACTIVE'
    FAILED = 'FAILED'


class AmazonResourceName(RootModel[constr(min_length=1, max_length=2048)]):
    root: constr(min_length=1, max_length=2048)


class AnalysisId(RootModel[str]):
    root: str


class AnalysisMessage(RootModel[str]):
    root: str


class AnalysisResultLevel(Enum):
    INFO = 'INFO'
    WARNING = 'WARNING'
    ERROR = 'ERROR'


class AnalysisResultLocationPath(RootModel[str]):
    root: str


class AnalysisStatus(Enum):
    RUNNING = 'RUNNING'
    COMPLETE = 'COMPLETE'
    FAILED = 'FAILED'


class AnalysisType(RootModel[str]):
    root: str


class AssetId(RootModel[str]):
    root: str


class AssetModelId(RootModel[str]):
    root: str


class AssetPropertyAlias(RootModel[str]):
    root: str


class AssetPropertyBooleanValue(RootModel[str]):
    root: str


class AssetPropertyDoubleValue(RootModel[str]):
    root: str


class AssetPropertyEntryId(RootModel[str]):
    root: str


class AssetPropertyId(RootModel[str]):
    root: str


class AssetPropertyIntegerValue(RootModel[str]):
    root: str


class AssetPropertyOffsetInNanos(RootModel[str]):
    root: str


class AssetPropertyQuality(RootModel[str]):
    root: str


class AssetPropertyStringValue(RootModel[str]):
    root: str


class AssetPropertyTimeInSeconds(RootModel[str]):
    root: str


class AssetPropertyTimestamp(BaseModel):
    offsetInNanos: Optional[AssetPropertyOffsetInNanos] = None
    timeInSeconds: AssetPropertyTimeInSeconds


class AssetPropertyVariant(BaseModel):
    booleanValue: Optional[AssetPropertyBooleanValue] = None
    doubleValue: Optional[AssetPropertyDoubleValue] = None
    integerValue: Optional[AssetPropertyIntegerValue] = None
    stringValue: Optional[AssetPropertyStringValue] = None


class AttributeJsonPath(
    RootModel[
        constr(
            pattern=r'^((`[\w\- ]+`)|([\w\-]+))(\.((`[\w- ]+`)|([\w\-]+)))*$',
            min_length=1,
            max_length=128,
        )
    ]
):
    root: constr(
        pattern=r'^((`[\w\- ]+`)|([\w\-]+))(\.((`[\w- ]+`)|([\w\-]+)))*$',
        min_length=1,
        max_length=128,
    )


class ComparisonOperator(Enum):
    GREATER = 'GREATER'
    GREATER_OR_EQUAL = 'GREATER_OR_EQUAL'
    LESS = 'LESS'
    LESS_OR_EQUAL = 'LESS_OR_EQUAL'
    EQUAL = 'EQUAL'
    NOT_EQUAL = 'NOT_EQUAL'


class Condition(RootModel[constr(max_length=512)]):
    root: constr(max_length=512)


class ContentExpression(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class DeleteAlarmModelRequest(BaseModel):
    pass


class DeleteAlarmModelResponse(BaseModel):
    pass


class DeleteDetectorModelRequest(BaseModel):
    pass


class DeleteDetectorModelResponse(BaseModel):
    pass


class DeleteInputRequest(BaseModel):
    pass


class DeleteInputResponse(BaseModel):
    pass


class DeliveryStreamName(RootModel[str]):
    root: str


class DescribeAlarmModelRequest(BaseModel):
    pass


class DescribeDetectorModelAnalysisRequest(BaseModel):
    pass


class DescribeDetectorModelAnalysisResponse(BaseModel):
    status: Optional[AnalysisStatus] = None


class DescribeDetectorModelRequest(BaseModel):
    pass


class DescribeInputRequest(BaseModel):
    pass


class DescribeLoggingOptionsRequest(BaseModel):
    pass


class DetectorModelArn(RootModel[str]):
    root: str


class DetectorModelDescription(RootModel[constr(max_length=128)]):
    root: constr(max_length=128)


class DetectorModelName(
    RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=128)]
):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=128)


class DetectorModelVersion(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class DetectorModelVersionStatus(Enum):
    ACTIVE = 'ACTIVE'
    ACTIVATING = 'ACTIVATING'
    INACTIVE = 'INACTIVE'
    DEPRECATED = 'DEPRECATED'
    DRAFT = 'DRAFT'
    PAUSED = 'PAUSED'
    FAILED = 'FAILED'


class DisabledOnInitialization(RootModel[bool]):
    root: bool


class DynamoKeyField(RootModel[str]):
    root: str


class DynamoKeyType(RootModel[str]):
    root: str


class DynamoKeyValue(RootModel[str]):
    root: str


class DynamoOperation(RootModel[str]):
    root: str


class DynamoTableName(RootModel[str]):
    root: str


class EmailSubject(RootModel[str]):
    root: str


class EvaluationMethod(Enum):
    BATCH = 'BATCH'
    SERIAL = 'SERIAL'


class EventName(RootModel[constr(max_length=128)]):
    root: constr(max_length=128)


class FirehoseSeparator(RootModel[constr(pattern=r'([\n\t])|(\r\n)|(,)')]):
    root: constr(pattern=r'([\n\t])|(\r\n)|(,)')


class FromEmail(RootModel[str]):
    root: str


class GetDetectorModelAnalysisResultsRequest(BaseModel):
    pass


class IdentityStoreId(RootModel[str]):
    root: str


class InitializationConfiguration(BaseModel):
    disabledOnInitialization: DisabledOnInitialization


class InputArn(RootModel[str]):
    root: str


class InputDescription(RootModel[constr(max_length=128)]):
    root: constr(max_length=128)


class InputName(
    RootModel[constr(pattern=r'^[a-zA-Z][a-zA-Z0-9_]*$', min_length=1, max_length=128)]
):
    root: constr(pattern=r'^[a-zA-Z][a-zA-Z0-9_]*$', min_length=1, max_length=128)


class InputProperty(RootModel[constr(min_length=1, max_length=512)]):
    root: constr(min_length=1, max_length=512)


class InputStatus(Enum):
    CREATING = 'CREATING'
    UPDATING = 'UPDATING'
    ACTIVE = 'ACTIVE'
    DELETING = 'DELETING'


class InternalFailureException(RootModel[Any]):
    root: Any


class InvalidRequestException(RootModel[Any]):
    root: Any


class IotEventsInputIdentifier(BaseModel):
    inputName: InputName


class IotSiteWiseAssetModelPropertyIdentifier(BaseModel):
    assetModelId: AssetModelId
    propertyId: AssetPropertyId


class IotSiteWiseInputIdentifier(BaseModel):
    iotSiteWiseAssetModelPropertyIdentifier: Optional[
        IotSiteWiseAssetModelPropertyIdentifier
    ] = None


class KeyValue(
    RootModel[constr(pattern=r'^[a-zA-Z0-9\-_:]+$', min_length=1, max_length=128)]
):
    root: constr(pattern=r'^[a-zA-Z0-9\-_:]+$', min_length=1, max_length=128)


class LimitExceededException(RootModel[Any]):
    root: Any


class ListAlarmModelVersionsRequest(BaseModel):
    pass


class ListAlarmModelsRequest(BaseModel):
    pass


class ListDetectorModelVersionsRequest(BaseModel):
    pass


class ListDetectorModelsRequest(BaseModel):
    pass


class ListInputsRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class LoggingEnabled(RootModel[bool]):
    root: bool


class LoggingLevel(Enum):
    ERROR = 'ERROR'
    INFO = 'INFO'
    DEBUG = 'DEBUG'


class MQTTTopic(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class MaxAnalysisResults(RootModel[int]):
    root: int


class MaxResults(RootModel[conint(ge=1, le=250)]):
    root: conint(ge=1, le=250)


class NextToken(RootModel[str]):
    root: str


class NotificationAdditionalMessage(RootModel[str]):
    root: str


class PayloadType(Enum):
    STRING = 'STRING'
    JSON = 'JSON'


class QueueUrl(RootModel[str]):
    root: str


class ResourceAlreadyExistsException(RootModel[Any]):
    root: Any


class ResourceInUseException(RootModel[Any]):
    root: Any


class ResourceName(RootModel[str]):
    root: str


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class RoutedResource(BaseModel):
    arn: Optional[AmazonResourceName] = None
    name: Optional[ResourceName] = None


class RoutedResources(RootModel[List[RoutedResource]]):
    root: List[RoutedResource]


class SMSSenderId(RootModel[str]):
    root: str


class SSOReferenceId(RootModel[str]):
    root: str


class Seconds(RootModel[conint(ge=1, le=31622400)]):
    root: conint(ge=1, le=31622400)


class ServiceUnavailableException(RootModel[Any]):
    root: Any


class Severity(RootModel[conint(ge=0, le=2147483647)]):
    root: conint(ge=0, le=2147483647)


class StartDetectorModelAnalysisResponse(BaseModel):
    analysisId: Optional[AnalysisId] = None


class StateName(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class StatusMessage(RootModel[str]):
    root: str


class TagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class Threshold(RootModel[constr(min_length=1, max_length=512)]):
    root: constr(min_length=1, max_length=512)


class ThrottlingException(RootModel[Any]):
    root: Any


class TimerName(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class Timestamp(RootModel[datetime]):
    root: datetime


class UnsupportedOperationException(RootModel[Any]):
    root: Any


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UpdateAlarmModelResponse(BaseModel):
    alarmModelArn: Optional[AlarmModelArn] = None
    alarmModelVersion: Optional[AlarmModelVersion] = None
    creationTime: Optional[Timestamp] = None
    lastUpdateTime: Optional[Timestamp] = None
    status: Optional[AlarmModelVersionStatus] = None


class UseBase64(RootModel[bool]):
    root: bool


class VariableName(
    RootModel[constr(pattern=r'^[a-zA-Z][a-zA-Z0-9_]*$', min_length=1, max_length=128)]
):
    root: constr(pattern=r'^[a-zA-Z][a-zA-Z0-9_]*$', min_length=1, max_length=128)


class VariableValue(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class InputIdentifier(BaseModel):
    iotEventsInputIdentifier: Optional[IotEventsInputIdentifier] = None
    iotSiteWiseInputIdentifier: Optional[IotSiteWiseInputIdentifier] = None


class InputRoutingsPostRequest(BaseModel):
    inputIdentifier: InputIdentifier = Field(
        ..., description=' The identifer of the input. '
    )
    maxResults: Optional[conint(ge=1, le=250)] = Field(
        None, description=' The maximum number of results to be returned per request. '
    )
    nextToken: Optional[str] = Field(
        None,
        description=' The token that you can use to return the next set of results. ',
    )


class AcknowledgeFlow(BaseModel):
    enabled: AcknowledgeFlowEnabled


class AlarmCapabilities(BaseModel):
    acknowledgeFlow: Optional[AcknowledgeFlow] = None
    initializationConfiguration: Optional[InitializationConfiguration] = None


class AlarmModelSummary(BaseModel):
    alarmModelDescription: Optional[AlarmModelDescription] = None
    alarmModelName: Optional[AlarmModelName] = None
    creationTime: Optional[Timestamp] = None


class AlarmModelVersionSummary(BaseModel):
    alarmModelArn: Optional[AlarmModelArn] = None
    alarmModelName: Optional[AlarmModelName] = None
    alarmModelVersion: Optional[AlarmModelVersion] = None
    creationTime: Optional[Timestamp] = None
    lastUpdateTime: Optional[Timestamp] = None
    roleArn: Optional[AmazonResourceName] = None
    status: Optional[AlarmModelVersionStatus] = None
    statusMessage: Optional[StatusMessage] = None


class AnalysisResultLocation(BaseModel):
    path: Optional[AnalysisResultLocationPath] = None


class AnalysisResultLocations(RootModel[List[AnalysisResultLocation]]):
    root: List[AnalysisResultLocation]


class AssetPropertyValue(BaseModel):
    quality: Optional[AssetPropertyQuality] = None
    timestamp: Optional[AssetPropertyTimestamp] = None
    value: Optional[AssetPropertyVariant] = None


class Attribute(BaseModel):
    jsonPath: AttributeJsonPath


class Attributes(RootModel[List[Attribute]]):
    root: List[Attribute] = Field(..., max_length=200, min_length=1)


class ClearTimerAction(BaseModel):
    timerName: TimerName


class CreateAlarmModelResponse(BaseModel):
    alarmModelArn: Optional[AlarmModelArn] = None
    alarmModelVersion: Optional[AlarmModelVersion] = None
    creationTime: Optional[Timestamp] = None
    lastUpdateTime: Optional[Timestamp] = None
    status: Optional[AlarmModelVersionStatus] = None


class DetectorDebugOption(BaseModel):
    detectorModelName: DetectorModelName
    keyValue: Optional[KeyValue] = None


class DetectorDebugOptions(RootModel[List[DetectorDebugOption]]):
    root: List[DetectorDebugOption] = Field(..., min_length=1)


class DetectorModelConfiguration(BaseModel):
    creationTime: Optional[Timestamp] = None
    detectorModelArn: Optional[DetectorModelArn] = None
    detectorModelDescription: Optional[DetectorModelDescription] = None
    detectorModelName: Optional[DetectorModelName] = None
    detectorModelVersion: Optional[DetectorModelVersion] = None
    evaluationMethod: Optional[EvaluationMethod] = None
    key: Optional[AttributeJsonPath] = None
    lastUpdateTime: Optional[Timestamp] = None
    roleArn: Optional[AmazonResourceName] = None
    status: Optional[DetectorModelVersionStatus] = None


class DetectorModelSummary(BaseModel):
    creationTime: Optional[Timestamp] = None
    detectorModelDescription: Optional[DetectorModelDescription] = None
    detectorModelName: Optional[DetectorModelName] = None


class DetectorModelVersionSummary(BaseModel):
    creationTime: Optional[Timestamp] = None
    detectorModelArn: Optional[DetectorModelArn] = None
    detectorModelName: Optional[DetectorModelName] = None
    detectorModelVersion: Optional[DetectorModelVersion] = None
    evaluationMethod: Optional[EvaluationMethod] = None
    lastUpdateTime: Optional[Timestamp] = None
    roleArn: Optional[AmazonResourceName] = None
    status: Optional[DetectorModelVersionStatus] = None


class EmailContent(BaseModel):
    additionalMessage: Optional[NotificationAdditionalMessage] = None
    subject: Optional[EmailSubject] = None


class InputConfiguration(BaseModel):
    creationTime: Timestamp
    inputArn: InputArn
    inputDescription: Optional[InputDescription] = None
    inputName: InputName
    lastUpdateTime: Timestamp
    status: InputStatus


class InputDefinition(BaseModel):
    attributes: Attributes


class InputSummary(BaseModel):
    creationTime: Optional[Timestamp] = None
    inputArn: Optional[InputArn] = None
    inputDescription: Optional[InputDescription] = None
    inputName: Optional[InputName] = None
    lastUpdateTime: Optional[Timestamp] = None
    status: Optional[InputStatus] = None


class IotSiteWiseAction(BaseModel):
    assetId: Optional[AssetId] = None
    entryId: Optional[AssetPropertyEntryId] = None
    propertyAlias: Optional[AssetPropertyAlias] = None
    propertyId: Optional[AssetPropertyId] = None
    propertyValue: Optional[AssetPropertyValue] = None


class ListInputRoutingsRequest(BaseModel):
    inputIdentifier: InputIdentifier
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None


class ListInputRoutingsResponse(BaseModel):
    nextToken: Optional[NextToken] = None
    routedResources: Optional[RoutedResources] = None


class LoggingOptions(BaseModel):
    detectorDebugOptions: Optional[DetectorDebugOptions] = None
    enabled: LoggingEnabled
    level: LoggingLevel
    roleArn: AmazonResourceName


class Payload(BaseModel):
    contentExpression: ContentExpression
    type: PayloadType


class PutLoggingOptionsRequest(BaseModel):
    loggingOptions: LoggingOptions


class ResetTimerAction(BaseModel):
    timerName: TimerName


class SNSTopicPublishAction(BaseModel):
    payload: Optional[Payload] = None
    targetArn: AmazonResourceName


class SSOIdentity(BaseModel):
    identityStoreId: IdentityStoreId
    userId: Optional[SSOReferenceId] = None


class SetTimerAction(BaseModel):
    durationExpression: Optional[VariableValue] = None
    seconds: Optional[Seconds] = None
    timerName: TimerName


class SetVariableAction(BaseModel):
    value: VariableValue
    variableName: VariableName


class SimpleRule(BaseModel):
    comparisonOperator: ComparisonOperator
    inputProperty: InputProperty
    threshold: Threshold


class SqsAction(BaseModel):
    payload: Optional[Payload] = None
    queueUrl: QueueUrl
    useBase64: Optional[UseBase64] = None


class Tag(BaseModel):
    key: TagKey
    value: TagValue


class Tags(RootModel[List[Tag]]):
    root: List[Tag]


class UpdateDetectorModelResponse(BaseModel):
    detectorModelConfiguration: Optional[DetectorModelConfiguration] = None


class UpdateInputRequest(BaseModel):
    inputDefinition: InputDefinition
    inputDescription: Optional[InputDescription] = None


class UpdateInputResponse(BaseModel):
    inputConfiguration: Optional[InputConfiguration] = None


class AlarmRule(BaseModel):
    simpleRule: Optional[SimpleRule] = None


class InputDefinition1(BaseModel):
    attributes: Optional[Attributes] = None


class InputsPostRequest(BaseModel):
    inputDefinition: InputDefinition1 = Field(
        ..., description='The definition of the input.'
    )
    inputDescription: Optional[constr(max_length=128)] = Field(
        None, description='A brief description of the input.'
    )
    inputName: constr(
        pattern=r'^[a-zA-Z][a-zA-Z0-9_]*$', min_length=1, max_length=128
    ) = Field(..., description='The name you want to give to the input.')
    tags: Optional[List[Tag]] = Field(
        None, description='Metadata that can be used to manage the input.'
    )


class InputsInputNamePutRequest(BaseModel):
    inputDefinition: InputDefinition1 = Field(
        ..., description='The definition of the input.'
    )
    inputDescription: Optional[constr(max_length=128)] = Field(
        None, description='A brief description of the input.'
    )


class LoggingOptions1(BaseModel):
    detectorDebugOptions: Optional[DetectorDebugOptions] = None
    enabled: Optional[LoggingEnabled] = None
    level: Optional[LoggingLevel] = None
    roleArn: Optional[AmazonResourceName] = None


class LoggingPutRequest(BaseModel):
    loggingOptions: LoggingOptions1 = Field(
        ..., description='The values of the AWS IoT Events logging options.'
    )


class TagsResourceArnPostRequest(BaseModel):
    tags: List[Tag] = Field(
        ..., description='The new or modified tags for the resource.'
    )


class AlarmModelSummaries(RootModel[List[AlarmModelSummary]]):
    root: List[AlarmModelSummary]


class AlarmModelVersionSummaries(RootModel[List[AlarmModelVersionSummary]]):
    root: List[AlarmModelVersionSummary]


class AnalysisResult(BaseModel):
    level: Optional[AnalysisResultLevel] = None
    locations: Optional[AnalysisResultLocations] = None
    message: Optional[AnalysisMessage] = None
    type: Optional[AnalysisType] = None


class AnalysisResults(RootModel[List[AnalysisResult]]):
    root: List[AnalysisResult]


class CreateDetectorModelResponse(BaseModel):
    detectorModelConfiguration: Optional[DetectorModelConfiguration] = None


class CreateInputRequest(BaseModel):
    inputDefinition: InputDefinition
    inputDescription: Optional[InputDescription] = None
    inputName: InputName
    tags: Optional[Tags] = None


class CreateInputResponse(BaseModel):
    inputConfiguration: Optional[InputConfiguration] = None


class DescribeLoggingOptionsResponse(BaseModel):
    loggingOptions: Optional[LoggingOptions] = None


class DetectorModelSummaries(RootModel[List[DetectorModelSummary]]):
    root: List[DetectorModelSummary]


class DetectorModelVersionSummaries(RootModel[List[DetectorModelVersionSummary]]):
    root: List[DetectorModelVersionSummary]


class DynamoDBAction(BaseModel):
    hashKeyField: DynamoKeyField
    hashKeyType: Optional[DynamoKeyType] = None
    hashKeyValue: DynamoKeyValue
    operation: Optional[DynamoOperation] = None
    payload: Optional[Payload] = None
    payloadField: Optional[DynamoKeyField] = None
    rangeKeyField: Optional[DynamoKeyField] = None
    rangeKeyType: Optional[DynamoKeyType] = None
    rangeKeyValue: Optional[DynamoKeyValue] = None
    tableName: DynamoTableName


class DynamoDBv2Action(BaseModel):
    payload: Optional[Payload] = None
    tableName: DynamoTableName


class FirehoseAction(BaseModel):
    deliveryStreamName: DeliveryStreamName
    payload: Optional[Payload] = None
    separator: Optional[FirehoseSeparator] = None


class GetDetectorModelAnalysisResultsResponse(BaseModel):
    analysisResults: Optional[AnalysisResults] = None
    nextToken: Optional[NextToken] = None


class Input(BaseModel):
    inputConfiguration: Optional[InputConfiguration] = None
    inputDefinition: Optional[InputDefinition] = None


class InputSummaries(RootModel[List[InputSummary]]):
    root: List[InputSummary]


class IotEventsAction(BaseModel):
    inputName: InputName
    payload: Optional[Payload] = None


class IotTopicPublishAction(BaseModel):
    mqttTopic: MQTTTopic
    payload: Optional[Payload] = None


class LambdaAction(BaseModel):
    functionArn: AmazonResourceName
    payload: Optional[Payload] = None


class ListAlarmModelVersionsResponse(BaseModel):
    alarmModelVersionSummaries: Optional[AlarmModelVersionSummaries] = None
    nextToken: Optional[NextToken] = None


class ListAlarmModelsResponse(BaseModel):
    alarmModelSummaries: Optional[AlarmModelSummaries] = None
    nextToken: Optional[NextToken] = None


class ListDetectorModelVersionsResponse(BaseModel):
    detectorModelVersionSummaries: Optional[DetectorModelVersionSummaries] = None
    nextToken: Optional[NextToken] = None


class ListDetectorModelsResponse(BaseModel):
    detectorModelSummaries: Optional[DetectorModelSummaries] = None
    nextToken: Optional[NextToken] = None


class ListInputsResponse(BaseModel):
    inputSummaries: Optional[InputSummaries] = None
    nextToken: Optional[NextToken] = None


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[Tags] = None


class NotificationTargetActions(BaseModel):
    lambdaAction: Optional[LambdaAction] = None


class RecipientDetail(BaseModel):
    ssoIdentity: Optional[SSOIdentity] = None


class RecipientDetails(RootModel[List[RecipientDetail]]):
    root: List[RecipientDetail] = Field(..., min_length=1)


class SMSConfiguration(BaseModel):
    additionalMessage: Optional[NotificationAdditionalMessage] = None
    recipients: RecipientDetails
    senderId: Optional[SMSSenderId] = None


class SMSConfigurations(RootModel[List[SMSConfiguration]]):
    root: List[SMSConfiguration] = Field(..., min_length=1)


class TagResourceRequest(BaseModel):
    tags: Tags


class Action(BaseModel):
    clearTimer: Optional[ClearTimerAction] = None
    dynamoDB: Optional[DynamoDBAction] = None
    dynamoDBv2: Optional[DynamoDBv2Action] = None
    firehose: Optional[FirehoseAction] = None
    iotEvents: Optional[IotEventsAction] = None
    iotSiteWise: Optional[IotSiteWiseAction] = None
    iotTopicPublish: Optional[IotTopicPublishAction] = None
    lambda_: Optional[LambdaAction] = Field(None, alias='lambda')
    resetTimer: Optional[ResetTimerAction] = None
    setTimer: Optional[SetTimerAction] = None
    setVariable: Optional[SetVariableAction] = None
    sns: Optional[SNSTopicPublishAction] = None
    sqs: Optional[SqsAction] = None


class Actions(RootModel[List[Action]]):
    root: List[Action]


class AlarmAction(BaseModel):
    dynamoDB: Optional[DynamoDBAction] = None
    dynamoDBv2: Optional[DynamoDBv2Action] = None
    firehose: Optional[FirehoseAction] = None
    iotEvents: Optional[IotEventsAction] = None
    iotSiteWise: Optional[IotSiteWiseAction] = None
    iotTopicPublish: Optional[IotTopicPublishAction] = None
    lambda_: Optional[LambdaAction] = Field(None, alias='lambda')
    sns: Optional[SNSTopicPublishAction] = None
    sqs: Optional[SqsAction] = None


class AlarmActions(RootModel[List[AlarmAction]]):
    root: List[AlarmAction]


class AlarmEventActions(BaseModel):
    alarmActions: Optional[AlarmActions] = None


class DescribeInputResponse(BaseModel):
    input: Optional[Input] = None


class EmailRecipients(BaseModel):
    to: Optional[RecipientDetails] = None


class Event(BaseModel):
    actions: Optional[Actions] = None
    condition: Optional[Condition] = None
    eventName: EventName


class Events(RootModel[List[Event]]):
    root: List[Event]


class OnEnterLifecycle(BaseModel):
    events: Optional[Events] = None


class OnExitLifecycle(BaseModel):
    events: Optional[Events] = None


class TransitionEvent(BaseModel):
    actions: Optional[Actions] = None
    condition: Condition
    eventName: EventName
    nextState: StateName


class TransitionEvents(RootModel[List[TransitionEvent]]):
    root: List[TransitionEvent]


class EmailConfiguration(BaseModel):
    content: Optional[EmailContent] = None
    from_: FromEmail = Field(..., alias='from')
    recipients: EmailRecipients


class EmailConfigurations(RootModel[List[EmailConfiguration]]):
    root: List[EmailConfiguration] = Field(..., min_length=1)


class NotificationAction(BaseModel):
    action: NotificationTargetActions
    emailConfigurations: Optional[EmailConfigurations] = None
    smsConfigurations: Optional[SMSConfigurations] = None


class NotificationActions(RootModel[List[NotificationAction]]):
    root: List[NotificationAction] = Field(..., min_length=1)


class OnInputLifecycle(BaseModel):
    events: Optional[Events] = None
    transitionEvents: Optional[TransitionEvents] = None


class State(BaseModel):
    onEnter: Optional[OnEnterLifecycle] = None
    onExit: Optional[OnExitLifecycle] = None
    onInput: Optional[OnInputLifecycle] = None
    stateName: StateName


class States(RootModel[List[State]]):
    root: List[State] = Field(..., min_length=1)


class AlarmNotification(BaseModel):
    notificationActions: Optional[NotificationActions] = None


class AlarmModelsPostRequest(BaseModel):
    alarmCapabilities: Optional[AlarmCapabilities] = Field(
        None,
        description='Contains the configuration information of alarm state changes.',
    )
    alarmEventActions: Optional[AlarmEventActions] = Field(
        None, description='Contains information about one or more alarm actions.'
    )
    alarmModelDescription: Optional[constr(max_length=128)] = Field(
        None, description='A description that tells you what the alarm model detects.'
    )
    alarmModelName: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=128
    ) = Field(
        ...,
        description="A unique name that helps you identify the alarm model. You can't change this name after you create the alarm model.",
    )
    alarmNotification: Optional[AlarmNotification] = Field(
        None, description='Contains information about one or more notification actions.'
    )
    alarmRule: AlarmRule = Field(..., description='Defines when your alarm is invoked.')
    key: Optional[
        constr(
            pattern=r'^((`[\w\- ]+`)|([\w\-]+))(\.((`[\w- ]+`)|([\w\-]+)))*$',
            min_length=1,
            max_length=128,
        )
    ] = Field(
        None,
        description='An input attribute used as a key to create an alarm. AWS IoT Events routes <a href="https://docs.aws.amazon.com/iotevents/latest/apireference/API_Input.html">inputs</a> associated with this key to the alarm.',
    )
    roleArn: constr(min_length=1, max_length=2048) = Field(
        ...,
        description='The ARN of the IAM role that allows the alarm to perform actions and access AWS resources. For more information, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>AWS General Reference</i>.',
    )
    severity: Optional[conint(ge=0, le=2147483647)] = Field(
        None,
        description='A non-negative integer that reflects the severity level of the alarm.',
    )
    tags: Optional[List[Tag]] = Field(
        None,
        description='<p>A list of key-value pairs that contain metadata for the alarm model. The tags help you manage the alarm model. For more information, see <a href="https://docs.aws.amazon.com/iotevents/latest/developerguide/tagging-iotevents.html">Tagging your AWS IoT Events resources</a> in the <i>AWS IoT Events Developer Guide</i>.</p> <p>You can create up to 50 tags for one alarm model.</p>',
    )


class AlarmModelsAlarmModelNamePostRequest(BaseModel):
    alarmCapabilities: Optional[AlarmCapabilities] = Field(
        None,
        description='Contains the configuration information of alarm state changes.',
    )
    alarmEventActions: Optional[AlarmEventActions] = Field(
        None, description='Contains information about one or more alarm actions.'
    )
    alarmModelDescription: Optional[constr(max_length=128)] = Field(
        None, description='The description of the alarm model.'
    )
    alarmNotification: Optional[AlarmNotification] = Field(
        None, description='Contains information about one or more notification actions.'
    )
    alarmRule: AlarmRule = Field(..., description='Defines when your alarm is invoked.')
    roleArn: constr(min_length=1, max_length=2048) = Field(
        ...,
        description='The ARN of the IAM role that allows the alarm to perform actions and access AWS resources. For more information, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>AWS General Reference</i>.',
    )
    severity: Optional[conint(ge=0, le=2147483647)] = Field(
        None,
        description='A non-negative integer that reflects the severity level of the alarm.',
    )


class DetectorModelDefinition1(BaseModel):
    initialStateName: Optional[StateName] = None
    states: Optional[States] = None


class AnalysisDetectorModelsPostRequest(BaseModel):
    detectorModelDefinition: DetectorModelDefinition1 = Field(
        ..., description='Information that defines how a detector operates.'
    )


class DetectorModelsPostRequest(BaseModel):
    detectorModelDefinition: DetectorModelDefinition1 = Field(
        ..., description='Information that defines how a detector operates.'
    )
    detectorModelDescription: Optional[constr(max_length=128)] = Field(
        None, description='A brief description of the detector model.'
    )
    detectorModelName: constr(
        pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=128
    ) = Field(..., description='The name of the detector model.')
    evaluationMethod: Optional[EvaluationMethod] = Field(
        None,
        description='Information about the order in which events are evaluated and how actions are executed. ',
    )
    key: Optional[
        constr(
            pattern=r'^((`[\w\- ]+`)|([\w\-]+))(\.((`[\w- ]+`)|([\w\-]+)))*$',
            min_length=1,
            max_length=128,
        )
    ] = Field(
        None,
        description='The input attribute key used to identify a device or system to create a detector (an instance of the detector model) and then to route each input received to the appropriate detector (instance). This parameter uses a JSON-path expression in the message payload of each input to specify the attribute-value pair that is used to identify the device associated with the input.',
    )
    roleArn: constr(min_length=1, max_length=2048) = Field(
        ...,
        description='The ARN of the role that grants permission to AWS IoT Events to perform its operations.',
    )
    tags: Optional[List[Tag]] = Field(
        None, description='Metadata that can be used to manage the detector model.'
    )


class DetectorModelsDetectorModelNamePostRequest(BaseModel):
    detectorModelDefinition: DetectorModelDefinition1 = Field(
        ..., description='Information that defines how a detector operates.'
    )
    detectorModelDescription: Optional[constr(max_length=128)] = Field(
        None, description='A brief description of the detector model.'
    )
    evaluationMethod: Optional[EvaluationMethod] = Field(
        None,
        description='Information about the order in which events are evaluated and how actions are executed. ',
    )
    roleArn: constr(min_length=1, max_length=2048) = Field(
        ...,
        description='The ARN of the role that grants permission to AWS IoT Events to perform its operations.',
    )


class CreateAlarmModelRequest(BaseModel):
    alarmCapabilities: Optional[AlarmCapabilities] = None
    alarmEventActions: Optional[AlarmEventActions] = None
    alarmModelDescription: Optional[AlarmModelDescription] = None
    alarmModelName: AlarmModelName
    alarmNotification: Optional[AlarmNotification] = None
    alarmRule: AlarmRule
    key: Optional[AttributeJsonPath] = None
    roleArn: AmazonResourceName
    severity: Optional[Severity] = None
    tags: Optional[Tags] = None


class DescribeAlarmModelResponse(BaseModel):
    alarmCapabilities: Optional[AlarmCapabilities] = None
    alarmEventActions: Optional[AlarmEventActions] = None
    alarmModelArn: Optional[AlarmModelArn] = None
    alarmModelDescription: Optional[AlarmModelDescription] = None
    alarmModelName: Optional[AlarmModelName] = None
    alarmModelVersion: Optional[AlarmModelVersion] = None
    alarmNotification: Optional[AlarmNotification] = None
    alarmRule: Optional[AlarmRule] = None
    creationTime: Optional[Timestamp] = None
    key: Optional[AttributeJsonPath] = None
    lastUpdateTime: Optional[Timestamp] = None
    roleArn: Optional[AmazonResourceName] = None
    severity: Optional[Severity] = None
    status: Optional[AlarmModelVersionStatus] = None
    statusMessage: Optional[StatusMessage] = None


class DetectorModelDefinition(BaseModel):
    initialStateName: StateName
    states: States


class StartDetectorModelAnalysisRequest(BaseModel):
    detectorModelDefinition: DetectorModelDefinition


class UpdateAlarmModelRequest(BaseModel):
    alarmCapabilities: Optional[AlarmCapabilities] = None
    alarmEventActions: Optional[AlarmEventActions] = None
    alarmModelDescription: Optional[AlarmModelDescription] = None
    alarmNotification: Optional[AlarmNotification] = None
    alarmRule: AlarmRule
    roleArn: AmazonResourceName
    severity: Optional[Severity] = None


class UpdateDetectorModelRequest(BaseModel):
    detectorModelDefinition: DetectorModelDefinition
    detectorModelDescription: Optional[DetectorModelDescription] = None
    evaluationMethod: Optional[EvaluationMethod] = None
    roleArn: AmazonResourceName


class CreateDetectorModelRequest(BaseModel):
    detectorModelDefinition: DetectorModelDefinition
    detectorModelDescription: Optional[DetectorModelDescription] = None
    detectorModelName: DetectorModelName
    evaluationMethod: Optional[EvaluationMethod] = None
    key: Optional[AttributeJsonPath] = None
    roleArn: AmazonResourceName
    tags: Optional[Tags] = None


class DetectorModel(BaseModel):
    detectorModelConfiguration: Optional[DetectorModelConfiguration] = None
    detectorModelDefinition: Optional[DetectorModelDefinition] = None


class DescribeDetectorModelResponse(BaseModel):
    detectorModel: Optional[DetectorModel] = None
